name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.1.app
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: xcodebuild test -scheme "ZenTuner_iOS" -destination platform="iOS Simulator,name=iPhone 14 Pro Max,OS=16.1"
  macos:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.1.app
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS
        run: xcodebuild build -scheme "ZenTuner_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  lint:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/realm/swiftlint:0.50.1
    steps:
      - uses: actions/checkout@v3
      - name: Run SwiftLint
        run: swiftlint lint --strict
