name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.app
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: xcodebuild test -scheme "ZenTuner_iOS" -destination platform="iOS Simulator,name=iPhone 12 Pro Max,OS=14.5"
  lint:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.app
    steps:
      - uses: actions/checkout@v1
      - name: Update Homebrew
        run: brew update
      - name: Install SwiftLint
        run: brew upgrade swiftlint || true
      - name: Run SwiftLint
        run: swiftlint lint --strict
